#pragma once

#include "NativeGameplayTags.h"

namespace ARPGGameplayTags
{
	// --- Ability ---
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Melee_LightAttack);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Melee_HeavyAttack);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Ranged_Fireball);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Dodge);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Charge);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Fireball);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_GroundSlam);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_DashStrike);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_WarCry);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ArcaneBeam);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_UsePotion);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_HitReact);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Enemy_Melee);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Enemy_Ranged);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Enemy_Charge);

	// --- State ---
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Stunned);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Invulnerable);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Attacking);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Charging);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Vulnerable);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Buffed_WarCry);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dashing);

	// --- Damage ---
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Physical);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Fire);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Ice);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Lightning);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Poison);

	// --- Data (SetByCaller keys for damage) ---
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage_Base);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage_Scaling);

	// --- Data (SetByCaller key for difficulty scaling) ---
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_DifficultyMultiplier);

	// --- Data (SetByCaller keys for attribute init) ---
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Init_Health);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Init_MaxHealth);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Init_Mana);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Init_MaxMana);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Init_Strength);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Init_Dexterity);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Init_Intelligence);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Init_Armor);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Init_AttackPower);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Init_CriticalChance);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Init_CriticalDamage);

	// --- Data (SetByCaller keys for resistance init) ---
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Init_FireResistance);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Init_IceResistance);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Init_LightningResistance);

	// --- Data (SetByCaller keys for progression init) ---
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Init_CurrentXP);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Init_XPToNextLevel);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Init_CharacterLevel);

	// --- Data (SetByCaller key for XP award) ---
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_XP_Amount);

	// --- Data (SetByCaller key for mana cost) ---
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_ManaCost);

	// --- Event ---
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_EnemyKilled);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combo_Open);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combo_Close);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combo_Input);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_MeleeHit);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_HitReact);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Death);

	// --- Cooldown ---
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Potion);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Fireball);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_GroundSlam);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_DashStrike);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_WarCry);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_ArcaneBeam);

	// --- Data (SetByCaller key for affix magnitude) ---
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Affix_Magnitude);

	// --- Item ---
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Weapon);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Weapon_Sword);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Weapon_Staff);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Weapon_Bow);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Armor);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Armor_Head);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Armor_Chest);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Armor_Legs);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Armor_Feet);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Accessory);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Accessory_Ring);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Accessory_Amulet);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Consumable);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Consumable_Potion);

	// --- Input ---
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_PrimaryAttack);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Dodge);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Sprint);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interact);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability1);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability2);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability3);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability4);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UsePotion);

	// --- Cooldown (Dodge) ---
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Dodge);

	// --- GameplayCue (visual/audio feedback) ---
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_HitImpact);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_HitImpact_Fire);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_HitImpact_Ice);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_HitImpact_Lightning);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Death);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Heal);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Buff_WarCry);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Stun);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Dodge);
	POF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_LevelUp);
}
