#include "Debug/ARPGLogCategories.h"

DEFINE_LOG_CATEGORY(LogARPGCombat);
DEFINE_LOG_CATEGORY(LogARPGAI);
DEFINE_LOG_CATEGORY(LogARPGInventory);
DEFINE_LOG_CATEGORY(LogARPGAbility);
DEFINE_LOG_CATEGORY(LogARPGQuest);
DEFINE_LOG_CATEGORY(LogARPGWorld);
DEFINE_LOG_CATEGORY(LogARPGSave);
DEFINE_LOG_CATEGORY(LogARPGUI);
DEFINE_LOG_CATEGORY(LogARPGAudio);
DEFINE_LOG_CATEGORY(LogARPGNetwork);
DEFINE_LOG_CATEGORY(LogARPGLifecycle);
